### ISSUE TITLE
Ambiguous Java class inside startup.py/PythonRegistrationProvider/

### ISSUE THREAD

**Issue by mohamed-ali** [sparklingpandas/sparklingml#46]
The following code snippet from `startup.py/PythonRegistrationProvider` seem to have an identation problem. And it also generates a PEP8 E305 problem. 

```
    class Java:
        package = "com.sparklingpandas.sparklingml.util.python"
        className = "PythonRegisterationProvider"
        implements = [package + "." + className]
```
- https://github.com/sparklingpandas/sparklingml/blob/master/sparklingml/startup.py#L70-L73 

@holdenk can you confirm that? I can submit a PR to fix it if so.

**Comment by mohamed-ali** [comment]
@holdenk do you confirm that this is an indentation problem? if so I can submit a PR to fix it.

**Comment by holdenk** [comment]
Sounds right, that would be awesome!

**Comment by mohamed-ali** [comment]
@holdenk 

I applied the change but it breaks the tests with the following error 

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/dali/Desktop/workspace/sparklingml/sparklingml/startup.py", line 116, in <module>
    pythonRegistrationObj.register(provider)
  File "/usr/local/lib/python2.7/dist-packages/py4j/java_gateway.py", line 1151, in __call__
    args_command, temp_args = self._build_args(*args)
  File "/usr/local/lib/python2.7/dist-packages/py4j/java_gateway.py", line 1121, in _build_args
    [get_command_part(arg, self.pool) for arg in new_args])
  File "/usr/local/lib/python2.7/dist-packages/py4j/protocol.py", line 290, in get_command_part
    command_part = REFERENCE_TYPE + parameter._get_object_id()
AttributeError: 'PythonRegistrationProvider' object has no attribute '_get_object_id'
[info] NltkPosPythonSuite:
[info] - verify that the transformer runs *** FAILED ***
[info]   java.util.concurrent.TimeoutException: Futures timed out after [10 seconds]
[info]   at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
[info]   at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
[info]   at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190)
[info]   at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
[info]   at scala.concurrent.Await$.result(package.scala:190)
[info]   at com.sparklingpandas.sparklingml.util.python.PythonTransformer$class.constructUDF(PythonTransformer.scala:25)
[info]   at com.sparklingpandas.sparklingml.feature.NltkPosPython.constructUDF(BasicPython.scala:10)
[info]   at com.sparklingpandas.sparklingml.util.python.PythonTransformer$class.transform(PythonTransformer.scala:40)
[info]   at com.sparklingpandas.sparklingml.feature.NltkPosPython.transform(BasicPython.scala:10)
[info]   at com.sparklingpandas.sparklingml.feature.NltkPosPythonSuite$$anonfun$1.apply(BasicPython.scala:24)
[info]   ...
18/03/27 09:12:15 WARN SparkContext: Using an existing SparkContext; some configuration may not take effect.
[info] StrLenPlusKPythonSuite:
[info] - verify that the transformer runs *** FAILED ***
[info]   java.util.concurrent.TimeoutException: Futures timed out after [10 seconds]
[info]   at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
[info]   at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
[info]   at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190)
[info]   at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
[info]   at scala.concurrent.Await$.result(package.scala:190)
[info]   at com.sparklingpandas.sparklingml.util.python.PythonTransformer$class.constructUDF(PythonTransformer.scala:25)
[info]   at com.sparklingpandas.sparklingml.feature.StrLenPlusKPython.constructUDF(BasicPython.scala:31)
[info]   at com.sparklingpandas.sparklingml.util.python.PythonTransformer$class.transform(PythonTransformer.scala:40)
[info]   at com.sparklingpandas.sparklingml.feature.StrLenPlusKPython.transform(BasicPython.scala:31)
[info]   at com.sparklingpandas.sparklingml.feature.StrLenPlusKPythonSuite$$anonfun$2.apply(BasicPython.scala:50)
[info]   ...
18/03/27 09:12:25 WARN SparkContext: Using an existing SparkContext; some configuration may not take effect.
[info] SpacyTokenizePythonSuite:
[info] - verify spacy tokenization works *** FAILED ***
[info]   java.util.concurrent.TimeoutException: Futures timed out after [10 seconds]
[info]   at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
[info]   at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
[info]   at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190)
[info]   at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
[info]   at scala.concurrent.Await$.result(package.scala:190)
[info]   at com.sparklingpandas.sparklingml.util.python.PythonTransformer$class.constructUDF(PythonTransformer.scala:25)
[info]   at com.sparklingpandas.sparklingml.feature.SpacyTokenizePython.constructUDF(BasicPython.scala:60)
[info]   at com.sparklingpandas.sparklingml.util.python.PythonTransformer$class.transform(PythonTransformer.scala:40)
[info]   at com.sparklingpandas.sparklingml.feature.SpacyTokenizePython.transform(BasicPython.scala:60)
[info]   at com.sparklingpandas.sparklingml.feature.SpacyTokenizePythonSuite$$anonfun$3.apply(BasicPython.scala:74)
[info]   ...
[info] SharedParamsCodeGenTest:
[info] - verify the generated code is up to date
[info] ScalaTest
[info] Run completed in 39 seconds, 325 milliseconds.
[info] Total number of tests run: 90
[info] Suites: completed 52, aborted 0
[info] Tests: succeeded 87, failed 3, canceled 0, ignored 0, pending 0
[info] *** 3 TESTS FAILED ***
[error] Failed: Total 90, Failed 3, Errors 0, Passed 87
[error] Failed tests:
[error] 	com.sparklingpandas.sparklingml.feature.SpacyTokenizePythonSuite
[error] 	com.sparklingpandas.sparklingml.feature.StrLenPlusKPythonSuite
[error] 	com.sparklingpandas.sparklingml.feature.NltkPosPythonSuite
[error] (test:test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 47 s, completed Mar 27, 2018 9:12:35 AM
```
But it's still a bit ambiguous to me, because I haven't seen a class as an attribute of another class before (at least in Python). Usually the class is wrapped within another method. Maybe it's something specific to py4j?

**Comment by mohamed-ali** [comment]
Now I get it, it's an inner class. It's explained in stackoverflow [here](https://stackoverflow.com/questions/719705/what-is-the-purpose-of-pythons-inner-classes). Closing this issue as it's no longer relevant.
